apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels: webserver
spec:
  replicaset: 3
  selector:         # 2 types of selectores --> 1. Equality Based selector   --> 2. Set-based selector
   matchLabels:
    type: webserver
  template:
   metadata:
    name: mypod
    labels:
     type: webserver
   spec:
    containers:
     - name: myn1
       image: nginx
